options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  database-user:
    default: neutron
    type: string
    description: Username for Neutron database access (if enabled)
  database:
    default: neutron
    type: string
    description: Database name for Neutron (if enabled)
  use-syslog:
    type: boolean
    default: False
    description: |
      If set to True, supporting services will log to syslog.
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  neutron-security-groups:
    type: boolean
    default: False
    description: |
      Use quantum for security group management.
  neutron-external-network:
    type: string
    default: ext_net
    description: Name of the external network for floating IP addresses provided by Neutron.
  neutron-plugin:
    default: ovs
    type: string
    description: |
      Neutron plugin to use for network management; supports
      .
        ovs - OpenvSwitch Plugin
        nvp - Nicira Network Virtualization Platform
      .
  # HA configuration settings
  vip:
    type: string
    description: "Virtual IP to use to front API services in ha configuration"
  vip_iface:
    type: string
    default: eth0
    description: "Network Interface where to place the Virtual IP"
  vip_cidr:
    type: int
    default: 24
    description: "Netmask that will be used for the Virtual IP"
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5404
    description: |
       Default multicast port number that will be used to communicate between
       HA Cluster nodes.
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  # Network configuration options
  # by default all access is over 'private-address'
  os-admin-network:
    type: string
    description: |
      The IP address and netmask of the OpenStack Admin network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for admin endpoints.
  os-internal-network:
    type: string
    description: |
      The IP address and netmask of the OpenStack Internal network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for internal endpoints.
  os-public-network:
    type: string
    description: |
      The IP address and netmask of the OpenStack Public network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for public endpoints.
  ssl_cert:
    type: string
    description: |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Neutron's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  ssl_key:
    type: string
    description: SSL key to use with certificate specified as ssl_cert.
  ssl_ca:
    type: string
    description: |
      SSL CA to use with the certificate and key provided - this is only
      required if you are providing a privately signed ssl_cert and ssl_key.
